# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue here! This space is [protected by our Code of Conduct](https://publiclab.org/conduct) - and we're here to help.
  Please follow the issue template to help us help you 👍🎉😄
  If you have screenshots [or a gif](https://publiclab.org/gifs/) to share demonstrating the issue, that's really helpful! 📸
  You can [make a gif](https://www.cockos.com/licecap/) too!
  Do join our [Gitter channel](https://gitter.im/publiclab/publiclab) for some brainstorming discussions.
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Thanks for opening this pull request! `Dangerbot` will test out your code and reply in a bit with some pointers and requests.
  There may be some errors, **but don't worry!** We're here to help! 👍🎉😄
  <br />
  One thing that can help to get started is to make sure you've included a link back to the original issue you're solving, in the format `fixes #0000` (for example). And to make sure the PR title describes what you're trying to do! (often it can be the same as the issue title) Thanks! 🙌
  <br />
  Then, you can [say hello in our chatroom](https://gitter.im/publiclab/publiclab) & share a link to this PR to get a review! 👋 ✅
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
  Congrats on merging your first pull request! 🙌🎉⚡️ 
  Your code will likely be published to https://mapknitter.org in the next few days.
  Now that you've completed this, you can help someone else take their first step!
  Reach out to someone else working on theirs on [Public Lab's code welcome page](https://code.publiclab.org#r=all) (where you'll now be featured as a recent contributor!). Thanks!
  <details>
  <summary><b>Help others take their first step</b></summary>
  <p>Now that you've merged your first pull request, you're the perfect person to help someone else out with this challenging first step. 🙌 </p>
  <p><a href="https://code.publiclab.org#r=all">https://code.publiclab.org</a></p>
  <p>Try looking at this list of `first-timers-only` issues, and see if someone else is waiting for feedback, or even stuck! 😕 </p>
  <p>People often get stuck at the same steps, so you might be able to help someone get unstuck, or help lead them to some documentation that'd help. Reach out and be encouraging and friendly! 😄 🎉 </p>
  <p>Read about <a href="https://github.com/publiclab/plots2/issues/3458">how to help support another newcomer here</a>, or find <a href="https://github.com/publiclab/plots2/labels/support">other ways to offer mutual support here</a>.</p>
  </details>

You can also join our <a href="https://gitter.im/publiclab/publiclab">Gitter channel</a> to connect with other contributors :inbox_tray:

# It is recommended to include as many gifs and emojis as possible
